support ghc881, migrate to new singletons
EmptyCase due to

Network/MQTT/Types.hs:289:1: error:
    Empty list of alternatives in case expression
      Use EmptyCase to allow this
    |
289 | singDecideInstance ''MsgType